
spring:
    config:
        import: security-variable.yml
    mvc: #static 파일들은 /static/~의 형식으로 불러오게 하라
        static-path-pattern: "/static/**"
    application: # 기본 설정
        name: Sns
    thymeleaf: #thymeleaf 설정
        cache: false
    datasource: #mybatis 설정
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/totragram
        username: root
        password: ${mysql.password}
    servlet:
        multipart:
            maxFileSize: 10MB # 파일 하나의 최대 크기
            maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

mybatis:
    mapper-locations: mappers/*Mapper.xml